//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Bild
    {
        public int Bild_ID { get; set; }
        public string Pfad { get; set; }
        public string BildName { get; set; }
        public int Auftrag_ID { get; set; }
    
        public virtual TBL_Auftrag TBL_Auftrag { get; set; }
    }
}
