//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Rueckerstattung
    {
        public int Rueckerstattung_ID { get; set; }
        public decimal Total { get; set; }
        public string Beschreibung { get; set; }
        public System.DateTime Erfassungsdatum { get; set; }
        public int Kreditor_ID { get; set; }
        public int Kategorie_ID { get; set; }
    
        public virtual TBL_Kategorie TBL_Kategorie { get; set; }
        public virtual TBL_Kreditor TBL_Kreditor { get; set; }
    }
}
