//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Dienstleistung
    {
        public TBL_Dienstleistung()
        {
            this.TBL_Auftrag = new HashSet<TBL_Auftrag>();
        }
    
        public int Dienstleistung_ID { get; set; }
        public decimal Preis { get; set; }
        public string Name { get; set; }
        public System.DateTime PreisStartDatum { get; set; }
        public System.DateTime PreisEndDatum { get; set; }
    
        public virtual ICollection<TBL_Auftrag> TBL_Auftrag { get; set; }
    }
}
