//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Termin
    {
        public int Termin_ID { get; set; }
        public System.DateTime T_Datum { get; set; }
        public System.DateTime T_Zeit { get; set; }
        public double T_DauerInMinuten { get; set; }
        public int Kunde_ID { get; set; }
    
        public virtual TBL_Kunde TBL_Kunde { get; set; }
    }
}
