//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Opt_Auftr
    {
        public int Auftrag_ID { get; set; }
        public int Option_ID { get; set; }
        public decimal OA_GesammtPreis { get; set; }
        public decimal OA_Anzahl { get; set; }
    
        public virtual TBL_Auftrag TBL_Auftrag { get; set; }
        public virtual TBL_Option TBL_Option { get; set; }
    }
}
