//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kreditor
    {
        public TBL_Kreditor()
        {
            this.TBL_Person = new HashSet<TBL_Person>();
            this.TBL_Rechnung = new HashSet<TBL_Rechnung>();
            this.TBL_Rueckerstattung = new HashSet<TBL_Rueckerstattung>();
        }
    
        public int Kreditor_ID { get; set; }
        public string Firma { get; set; }
        public bool KRD_Geloescht { get; set; }
    
        public virtual ICollection<TBL_Person> TBL_Person { get; set; }
        public virtual ICollection<TBL_Rechnung> TBL_Rechnung { get; set; }
        public virtual ICollection<TBL_Rueckerstattung> TBL_Rueckerstattung { get; set; }
    }
}
