//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Person
    {
        public TBL_Person()
        {
            this.TBL_Auftrag = new HashSet<TBL_Auftrag>();
            this.TBL_Rechnung = new HashSet<TBL_Rechnung>();
            this.TBL_Rueckerstattung = new HashSet<TBL_Rueckerstattung>();
            this.TBL_Termin = new HashSet<TBL_Termin>();
        }
    
        public int Person_ID { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Adresse { get; set; }
        public int PLZ { get; set; }
        public string Land { get; set; }
        public string Ortschaft { get; set; }
        public string TelPrivat { get; set; }
        public string TelFirma { get; set; }
        public string TelMobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public System.DateTime Erfassungsdatum { get; set; }
        public bool Geloescht { get; set; }
        public Nullable<int> Kunde_ID { get; set; }
        public Nullable<int> Kreditor_ID { get; set; }
    
        public virtual ICollection<TBL_Auftrag> TBL_Auftrag { get; set; }
        public virtual TBL_Kreditor TBL_Kreditor { get; set; }
        public virtual TBL_Kunde TBL_Kunde { get; set; }
        public virtual ICollection<TBL_Rechnung> TBL_Rechnung { get; set; }
        public virtual ICollection<TBL_Rueckerstattung> TBL_Rueckerstattung { get; set; }
        public virtual ICollection<TBL_Termin> TBL_Termin { get; set; }
    }
}
