//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kunde
    {
        public TBL_Kunde()
        {
            this.TBL_Person = new HashSet<TBL_Person>();
        }
    
        public int Kunde_ID { get; set; }
        public bool Erinnerung { get; set; }
    
        public virtual ICollection<TBL_Person> TBL_Person { get; set; }
    }
}
