//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kunde
    {
        public TBL_Kunde()
        {
            this.TBL_Auftrag = new HashSet<TBL_Auftrag>();
            this.TBL_Termin = new HashSet<TBL_Termin>();
        }
    
        public int Kunde_ID { get; set; }
        public string K_Name { get; set; }
        public string K_Vorname { get; set; }
        public string K_Adresse { get; set; }
        public string K_TelPrivat { get; set; }
        public string K_TelMobile { get; set; }
        public string K_Email { get; set; }
        public System.DateTime K_Erfassungsdatum { get; set; }
        public bool K_Erinnerung { get; set; }
        public bool K_Geloescht { get; set; }
        public int PLZ { get; set; }
    
        public virtual ICollection<TBL_Auftrag> TBL_Auftrag { get; set; }
        public virtual ICollection<TBL_Termin> TBL_Termin { get; set; }
        public virtual TBL_Ort TBL_Ort { get; set; }
    }
}
