//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_Buchhaltung.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Ort
    {
        public TBL_Ort()
        {
            this.TBL_Kreditor = new HashSet<TBL_Kreditor>();
            this.TBL_Kunde = new HashSet<TBL_Kunde>();
        }
    
        public int PLZ { get; set; }
        public string Ortschaft { get; set; }
        public string Land { get; set; }
    
        public virtual ICollection<TBL_Kreditor> TBL_Kreditor { get; set; }
        public virtual ICollection<TBL_Kunde> TBL_Kunde { get; set; }
    }
}
